package com.howling.openedagain.core

data class DetectionConfig(
    val quickReentryMs: Long = 30_000,
    val shortOpenMs: Long = 5_000,
    val patrolWindowMs: Long = 180_000,
    val patrolRareApps: Int = 5,
    val patrolEpicApps: Int = 8,
    val wanderingWindowMs: Long = 300_000,
    val wanderingRareSwitches: Int = 8,
    val wanderingEpicSwitches: Int = 12,
    val hiddenLoopWindowMs: Long = 300_000,
    val hiddenLoopSwitches: Int = 6,
    val sessionGapMs: Long = 120_000,
    val unlockAssociationMs: Long = 10_000,
    /** Adjacent visits to the same package closer than this are merged. Handles activity-to-activity transitions. */
    val sameAppMergeGapMs: Long = 1_500,
    val nightStartHour: Int = 1,
    val nightEndHour: Int = 5,
    val dawnStartHour: Int = 3,
    val dawnEndHour: Int = 5,
    val hiddenNightMinUnlocks: Int = 5,
    val hiddenNightMaxTotalUsageMs: Long = 15 * 60_000L,
    val hiddenNightMaxSessionMs: Long = 2 * 60_000L,
    /** Prevent pathological zero/near-zero visits generated by noisy events. */
    val minimumVisitMs: Long = 250
)
